spring:
  cloud.config.server.git.uri: ${CONFIG_GIT_REPO_URI:https://github.com/TwigCodes/twig-config-files.git}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
# 定义服务端口
server:
  port: ${SERVER_PORT:8888}
logging:
  level:
    org.springframework.cloud: ERROR
    com.twigcodes.configserver: ERROR
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/
management:
  endpoints:
    # 让所有监控接口都接受 web 访问
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---

spring:
  profiles: prod
