spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TwigCodes/twig-config-files.git
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# 定义服务端口
server:
  port: 8888
logging:
  level:
    org.springframework:
      cloud: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    # 让所有监控接口都接受 web 访问
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---

spring:
  profiles: prod
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    hostname: configsever
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
